### PR TITLE
PPCDEV-15235 users docs for 16.19

### PR DESCRIPTION
**Pull request by chriskicker**

### CODE REVIEW

**Comment by JacekClearcode** [comment]
https://developers.piwik.pro/en/feature-ppcdev-15235-middleware-16.19/ For checking pleasure

**Comment by chriskicker** [comment]
> [developers.piwik.pro/en/feature-ppcdev-15235-middleware-16.19/platform/authorized_api/users/users_api.html](https://developers.piwik.pro/en/feature-ppcdev-15235-middleware-16.19/platform/authorized_api/users/users_api.html) For checking pleasure

meh, why status code is not generated [above that response sample](https://developers.piwik.pro/en/feature-ppcdev-15235-middleware-16.19/platform/authorized_api/users/users_api.html#operation/api_users_me_change_password_v2)? :disappointed: 
[
Here you can see](https://piwikpro-artifactory.s3.eu-central-1.amazonaws.com/long/platform/api-docs/master/index.html?path=./users/public_v2.yaml#operation/api_users_me_change_password_v2) that it's rendered. It would be nice to update some dependencies, right now it could misinform the user.

**Comment by JacekClearcode** [comment]
We wont update packages for now

**Comment by JacekClearcode** [comment]
Additionally I checked the code for that. I'll try to write some custome CSS for this to "appear". Better than nothing ;)

**Review by JacekClearcode — APPROVED** [review]

**Pull request merged**
