### PR TITLE
PPTECHDOC-66 Added deprecation warning for reportning API

### PR DESCRIPTION
**Pull request by RomanSek**
2020-03-10T111510

### CODE REVIEW

**Comment by RomanSek** [comment]
2020-03-11T114152
Let me know if this is the look we're going for.

**Comment by zaan** [comment]
Looks good!
I think that it would be good to add some separator between deprecation notice and the content of the docs or at least a bit more space.

**Comment by RomanSek** [comment]
I don't see option to format it this way. Looks like only alternative format will  look this way:
2020-03-11T145727

**Comment by zaan** [comment]
OK then, let's go with the first option with spaces between paragraphs.

**Pull request merged**
