### PR TITLE
PPCDEV-7059 Apps api docs

### PR DESCRIPTION
**Pull request by mrfijas**
* gdpr manual mode
* cookie expiration period
* small fixes of existing docs

### CODE REVIEW

**Comment by RomanSek** [comment]
I want to confirm that these changes were introduced in version 6.2 because they look to me like documentation corrections. If these are in fact only corrections - we should merge them into first version that introduced there elements. It looks like we added changed file in v6.1.

**Comment by mrfijas** [comment]
@RomanSek you're right only two fields were added in `6.1`, rest are small fixes that we've found in the meantime.. so I'll add another "backport PR" to `6.1` with corresponding changes, thanks for good eye!

**Comment by RomanSek** [comment]
@mrfijas I rebased it to corrected version of 6.2. Let me know if changes match what you intended.

**Comment by mrfijas** [comment]
@RomanSek yup, it's intended change, thanks

**Pull request merged**
