### PR TITLE
Fixing example of the Product Custom Dimensions (PPTT-4310)

### PR DESCRIPTION
**Pull request by wronan**
How long do I have to wait for https://developers.piwik.pro/en/pptt-4310_product_cus_dim_example_fix/data_collection/api/http_api.html ? 
This time I have to rely on the on online version since local dev env (docker-compose based) is failing.

### CODE REVIEW

**Comment by azarecki** [comment]
AFAIK online versions are created manually by developers.piwik.pro admins (Romek/Jacek)

**Comment by kororokke** [comment]
https://developers.piwik.pro/en/pptt-4310_product_cus_dim_example_fix/  Also - master?

**Comment by wronan** [comment]
@kororokke it still looks poorly:
image

Is there any multi-line code block that I could use?

**Comment by kororokke** [comment]
I'm gonna add some css tomorrow morning to fix this

**Comment by kororokke** [comment]
Should be fixed - clear cache to check.

**Comment by kororokke** [comment]
Also @wronan what version is this?

**Pull request merged**
