### PR TITLE
PPNA-5446 update Ecommerce documentation

### PR DESCRIPTION
**Pull request by dpaluch-piw**
[Preview](https://developers.piwik.pro/en/feature-new-ecommerce/data_collection/api/http_api.html)

### CODE REVIEW

**Comment by kororokke** [comment]
Will be merged when feature is ready

**Review by RomanSek — COMMENTED** [review]
[Preview](https://developers.piwik.pro/en/feature-new-ecommerce/data_collection/api/http_api.html)

**Review by janusz-piechota-piwik — APPROVED** [review]

**Comment by RomanSek** [comment]
@dpaluch-piw We have a branch for [new ecommerce](https://github.com/PiwikPRO/PPMS-PublicDocs/tree/feature/new-ecommerce). You can merge your changes there if they are finalized to better organize docs for that feature.

**Comment by kororokke** [comment]
We know @RomanSek we know. We wont do it for now iirc

**Pull request merged**
